#!/bin/bash -e

case "$1" in
    configure)
        plymouth-set-default-theme endlessos
        ;;

    abort-upgrade|abort-deconfigure|abort-remove)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac

exit 0
