#!/bin/bash -e

case "$1" in
    configure)
	update-alternatives \
		--install /lib/plymouth/themes/default.plymouth default.plymouth \
		/lib/plymouth/themes/endlessos/endlessos.plymouth 10

	if which update-initramfs >/dev/null 2>&1
	then
	    update-initramfs -u
	fi
	;;

    abort-upgrade|abort-deconfigure|abort-remove)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

exit 0
